#ifndef CAMDEV_TYPEDEF_H
#define CAMDEV_TYPEDEF_H

#include <string>

namespace DevLayer{

#define IMG_BUF_LEN 1024*1024   // 1M
#define IMGHEAD std::string("IMGHEAD")
#define IMGTAIL std::string("IMGTAIL")
enum CAM_DEV_IMG_TYPE{CAM_DEV_IMG_TYPE_COLOR = 0, CAM_DEV_IMG_TYPE_DEPTH, CAM_DEV_IMG_TYPE_IR};
enum CAM_DEV_TYPE{CAM_DEV_TYPE_OPENCV = 0, CAM_DEV_TYPE_PRIMESENSE, CAM_DEV_TYPE_REALSENSE_435, CAM_DEV_TYPE_REALSENSE_455};

}

#endif
