#ifndef TCPDEV_TYPEDEF_H
#define TCPDEV_TYPEDEF_H

namespace DevLayer{

// NONE: 最低权限，OBSERVER: 观察者权限, OPERATOR: 操作员权限，ROOT: 管理员权限
enum AUTHORITY_TYPE{AUTHORITY_NONE, AUTHORITY_OBSERVER, AUTHORITY_OPERATOR, AUTHORITY_ROOT};
enum TCPCONDEV_TYPE{TCPCONDEV_CLIENT, TCPCONDEV_SERVER};
enum {MSG_LABEL_GET = 0, MSG_LABEL_SET = 500, MSG_LABEL_DEV = 1000, MSG_LABEL_GET_DEV_FINISH, MSG_LABEL_GET_AUTHORITY, MSG_LABEL_SET_AUTHORITY, MSG_PERMISSION_DENIED = 2000};

}

#endif