// Generated by gencpp from file robot_package/Claw.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_CLAW_H
#define ROBOT_PACKAGE_MESSAGE_CLAW_H

#include <ros/service_traits.h>


#include <robot_package/ClawRequest.h>
#include <robot_package/ClawResponse.h>


namespace robot_package
{

struct Claw
{

typedef ClawRequest Request;
typedef ClawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Claw
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::Claw > {
  static const char* value()
  {
    return "e74a584008af7a48800c53c1a71e78cb";
  }

  static const char* value(const ::robot_package::Claw&) { return value(); }
};

template<>
struct DataType< ::robot_package::Claw > {
  static const char* value()
  {
    return "robot_package/Claw";
  }

  static const char* value(const ::robot_package::Claw&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::ClawRequest> should match
// service_traits::MD5Sum< ::robot_package::Claw >
template<>
struct MD5Sum< ::robot_package::ClawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::Claw >::value();
  }
  static const char* value(const ::robot_package::ClawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::ClawRequest> should match
// service_traits::DataType< ::robot_package::Claw >
template<>
struct DataType< ::robot_package::ClawRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::Claw >::value();
  }
  static const char* value(const ::robot_package::ClawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::ClawResponse> should match
// service_traits::MD5Sum< ::robot_package::Claw >
template<>
struct MD5Sum< ::robot_package::ClawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::Claw >::value();
  }
  static const char* value(const ::robot_package::ClawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::ClawResponse> should match
// service_traits::DataType< ::robot_package::Claw >
template<>
struct DataType< ::robot_package::ClawResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::Claw >::value();
  }
  static const char* value(const ::robot_package::ClawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_CLAW_H
