// Generated by gencpp from file robot_package/ImageToFrameRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_IMAGETOFRAMEREQUEST_H
#define ROBOT_PACKAGE_MESSAGE_IMAGETOFRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace robot_package
{
template <class ContainerAllocator>
struct ImageToFrameRequest_
{
  typedef ImageToFrameRequest_<ContainerAllocator> Type;

  ImageToFrameRequest_()
    : image()
    , armIndex(0)
    , position()  {
    }
  ImageToFrameRequest_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , armIndex(0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef int8_t _armIndex_type;
  _armIndex_type armIndex;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::robot_package::ImageToFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::ImageToFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageToFrameRequest_

typedef ::robot_package::ImageToFrameRequest_<std::allocator<void> > ImageToFrameRequest;

typedef boost::shared_ptr< ::robot_package::ImageToFrameRequest > ImageToFrameRequestPtr;
typedef boost::shared_ptr< ::robot_package::ImageToFrameRequest const> ImageToFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::ImageToFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::ImageToFrameRequest_<ContainerAllocator1> & lhs, const ::robot_package::ImageToFrameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image == rhs.image &&
    lhs.armIndex == rhs.armIndex &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::ImageToFrameRequest_<ContainerAllocator1> & lhs, const ::robot_package::ImageToFrameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::ImageToFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::ImageToFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::ImageToFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d77936b4adceabd54a5fc3e51d5165bb";
  }

  static const char* value(const ::robot_package::ImageToFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd77936b4adceabd5ULL;
  static const uint64_t static_value2 = 0x4a5fc3e51d5165bbULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/ImageToFrameRequest";
  }

  static const char* value(const ::robot_package::ImageToFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image\n"
"int8 armIndex\n"
"float32[] position\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_package::ImageToFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.armIndex);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageToFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::ImageToFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::ImageToFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "armIndex: ";
    Printer<int8_t>::stream(s, indent + "  ", v.armIndex);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_IMAGETOFRAMEREQUEST_H
