// Generated by gencpp from file robot_package/ImageToFrame.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_IMAGETOFRAME_H
#define ROBOT_PACKAGE_MESSAGE_IMAGETOFRAME_H

#include <ros/service_traits.h>


#include <robot_package/ImageToFrameRequest.h>
#include <robot_package/ImageToFrameResponse.h>


namespace robot_package
{

struct ImageToFrame
{

typedef ImageToFrameRequest Request;
typedef ImageToFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageToFrame
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::ImageToFrame > {
  static const char* value()
  {
    return "98dec61900beef2fa84144aa65b13d5c";
  }

  static const char* value(const ::robot_package::ImageToFrame&) { return value(); }
};

template<>
struct DataType< ::robot_package::ImageToFrame > {
  static const char* value()
  {
    return "robot_package/ImageToFrame";
  }

  static const char* value(const ::robot_package::ImageToFrame&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::ImageToFrameRequest> should match
// service_traits::MD5Sum< ::robot_package::ImageToFrame >
template<>
struct MD5Sum< ::robot_package::ImageToFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::ImageToFrame >::value();
  }
  static const char* value(const ::robot_package::ImageToFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::ImageToFrameRequest> should match
// service_traits::DataType< ::robot_package::ImageToFrame >
template<>
struct DataType< ::robot_package::ImageToFrameRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::ImageToFrame >::value();
  }
  static const char* value(const ::robot_package::ImageToFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::ImageToFrameResponse> should match
// service_traits::MD5Sum< ::robot_package::ImageToFrame >
template<>
struct MD5Sum< ::robot_package::ImageToFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::ImageToFrame >::value();
  }
  static const char* value(const ::robot_package::ImageToFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::ImageToFrameResponse> should match
// service_traits::DataType< ::robot_package::ImageToFrame >
template<>
struct DataType< ::robot_package::ImageToFrameResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::ImageToFrame >::value();
  }
  static const char* value(const ::robot_package::ImageToFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_IMAGETOFRAME_H
