// Generated by gencpp from file robot_package/ImageToFrameResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_IMAGETOFRAMERESPONSE_H
#define ROBOT_PACKAGE_MESSAGE_IMAGETOFRAMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct ImageToFrameResponse_
{
  typedef ImageToFrameResponse_<ContainerAllocator> Type;

  ImageToFrameResponse_()
    : terminal()
    , result(0)
    , strRt()  {
    }
  ImageToFrameResponse_(const ContainerAllocator& _alloc)
    : terminal(_alloc)
    , result(0)
    , strRt(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _terminal_type;
  _terminal_type terminal;

   typedef int32_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _strRt_type;
  _strRt_type strRt;





  typedef boost::shared_ptr< ::robot_package::ImageToFrameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::ImageToFrameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImageToFrameResponse_

typedef ::robot_package::ImageToFrameResponse_<std::allocator<void> > ImageToFrameResponse;

typedef boost::shared_ptr< ::robot_package::ImageToFrameResponse > ImageToFrameResponsePtr;
typedef boost::shared_ptr< ::robot_package::ImageToFrameResponse const> ImageToFrameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::ImageToFrameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::ImageToFrameResponse_<ContainerAllocator1> & lhs, const ::robot_package::ImageToFrameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.terminal == rhs.terminal &&
    lhs.result == rhs.result &&
    lhs.strRt == rhs.strRt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::ImageToFrameResponse_<ContainerAllocator1> & lhs, const ::robot_package::ImageToFrameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::ImageToFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::ImageToFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::ImageToFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1850009fee622b55df0c6903f94f4582";
  }

  static const char* value(const ::robot_package::ImageToFrameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1850009fee622b55ULL;
  static const uint64_t static_value2 = 0xdf0c6903f94f4582ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/ImageToFrameResponse";
  }

  static const char* value(const ::robot_package::ImageToFrameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] terminal\n"
"int32 result\n"
"string strRt\n"
;
  }

  static const char* value(const ::robot_package::ImageToFrameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.terminal);
      stream.next(m.result);
      stream.next(m.strRt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageToFrameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::ImageToFrameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::ImageToFrameResponse_<ContainerAllocator>& v)
  {
    s << indent << "terminal[]" << std::endl;
    for (size_t i = 0; i < v.terminal.size(); ++i)
    {
      s << indent << "  terminal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.terminal[i]);
    }
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "strRt: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.strRt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_IMAGETOFRAMERESPONSE_H
