// Generated by gencpp from file robot_package/MoveABSJFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_MOVEABSJFEEDBACK_H
#define ROBOT_PACKAGE_MESSAGE_MOVEABSJFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct MoveABSJFeedback_
{
  typedef MoveABSJFeedback_<ContainerAllocator> Type;

  MoveABSJFeedback_()
    : current_state(0.0)  {
    }
  MoveABSJFeedback_(const ContainerAllocator& _alloc)
    : current_state(0.0)  {
  (void)_alloc;
    }



   typedef float _current_state_type;
  _current_state_type current_state;





  typedef boost::shared_ptr< ::robot_package::MoveABSJFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::MoveABSJFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveABSJFeedback_

typedef ::robot_package::MoveABSJFeedback_<std::allocator<void> > MoveABSJFeedback;

typedef boost::shared_ptr< ::robot_package::MoveABSJFeedback > MoveABSJFeedbackPtr;
typedef boost::shared_ptr< ::robot_package::MoveABSJFeedback const> MoveABSJFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::MoveABSJFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::MoveABSJFeedback_<ContainerAllocator1> & lhs, const ::robot_package::MoveABSJFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_state == rhs.current_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::MoveABSJFeedback_<ContainerAllocator1> & lhs, const ::robot_package::MoveABSJFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::MoveABSJFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::MoveABSJFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::MoveABSJFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "250debf4867cbd8be718efdde213baf6";
  }

  static const char* value(const ::robot_package::MoveABSJFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x250debf4867cbd8bULL;
  static const uint64_t static_value2 = 0xe718efdde213baf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/MoveABSJFeedback";
  }

  static const char* value(const ::robot_package::MoveABSJFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback 消息\n"
"float32 current_state\n"
;
  }

  static const char* value(const ::robot_package::MoveABSJFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveABSJFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::MoveABSJFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::MoveABSJFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_state: ";
    Printer<float>::stream(s, indent + "  ", v.current_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_MOVEABSJFEEDBACK_H
