// Generated by gencpp from file robot_package/MoveABSJ.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_MOVEABSJ_H
#define ROBOT_PACKAGE_MESSAGE_MOVEABSJ_H

#include <ros/service_traits.h>


#include <robot_package/MoveABSJRequest.h>
#include <robot_package/MoveABSJResponse.h>


namespace robot_package
{

struct MoveABSJ
{

typedef MoveABSJRequest Request;
typedef MoveABSJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveABSJ
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::MoveABSJ > {
  static const char* value()
  {
    return "9f5c1d959c1e4ebf958c5633996996d5";
  }

  static const char* value(const ::robot_package::MoveABSJ&) { return value(); }
};

template<>
struct DataType< ::robot_package::MoveABSJ > {
  static const char* value()
  {
    return "robot_package/MoveABSJ";
  }

  static const char* value(const ::robot_package::MoveABSJ&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::MoveABSJRequest> should match
// service_traits::MD5Sum< ::robot_package::MoveABSJ >
template<>
struct MD5Sum< ::robot_package::MoveABSJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::MoveABSJ >::value();
  }
  static const char* value(const ::robot_package::MoveABSJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::MoveABSJRequest> should match
// service_traits::DataType< ::robot_package::MoveABSJ >
template<>
struct DataType< ::robot_package::MoveABSJRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::MoveABSJ >::value();
  }
  static const char* value(const ::robot_package::MoveABSJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::MoveABSJResponse> should match
// service_traits::MD5Sum< ::robot_package::MoveABSJ >
template<>
struct MD5Sum< ::robot_package::MoveABSJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::MoveABSJ >::value();
  }
  static const char* value(const ::robot_package::MoveABSJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::MoveABSJResponse> should match
// service_traits::DataType< ::robot_package::MoveABSJ >
template<>
struct DataType< ::robot_package::MoveABSJResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::MoveABSJ >::value();
  }
  static const char* value(const ::robot_package::MoveABSJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_MOVEABSJ_H
