// Generated by gencpp from file robot_package/MoveL.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_MOVEL_H
#define ROBOT_PACKAGE_MESSAGE_MOVEL_H

#include <ros/service_traits.h>


#include <robot_package/MoveLRequest.h>
#include <robot_package/MoveLResponse.h>


namespace robot_package
{

struct MoveL
{

typedef MoveLRequest Request;
typedef MoveLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveL
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::MoveL > {
  static const char* value()
  {
    return "cb6915dd75fcbacce2cfbc55a90a7b92";
  }

  static const char* value(const ::robot_package::MoveL&) { return value(); }
};

template<>
struct DataType< ::robot_package::MoveL > {
  static const char* value()
  {
    return "robot_package/MoveL";
  }

  static const char* value(const ::robot_package::MoveL&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::MoveLRequest> should match
// service_traits::MD5Sum< ::robot_package::MoveL >
template<>
struct MD5Sum< ::robot_package::MoveLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::MoveL >::value();
  }
  static const char* value(const ::robot_package::MoveLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::MoveLRequest> should match
// service_traits::DataType< ::robot_package::MoveL >
template<>
struct DataType< ::robot_package::MoveLRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::MoveL >::value();
  }
  static const char* value(const ::robot_package::MoveLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::MoveLResponse> should match
// service_traits::MD5Sum< ::robot_package::MoveL >
template<>
struct MD5Sum< ::robot_package::MoveLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::MoveL >::value();
  }
  static const char* value(const ::robot_package::MoveLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::MoveLResponse> should match
// service_traits::DataType< ::robot_package::MoveL >
template<>
struct DataType< ::robot_package::MoveLResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::MoveL >::value();
  }
  static const char* value(const ::robot_package::MoveLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_MOVEL_H
