// Generated by gencpp from file robot_package/MoveJ.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_MOVEJ_H
#define ROBOT_PACKAGE_MESSAGE_MOVEJ_H

#include <ros/service_traits.h>


#include <robot_package/MoveJRequest.h>
#include <robot_package/MoveJResponse.h>


namespace robot_package
{

struct MoveJ
{

typedef MoveJRequest Request;
typedef MoveJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJ
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::MoveJ > {
  static const char* value()
  {
    return "cb6915dd75fcbacce2cfbc55a90a7b92";
  }

  static const char* value(const ::robot_package::MoveJ&) { return value(); }
};

template<>
struct DataType< ::robot_package::MoveJ > {
  static const char* value()
  {
    return "robot_package/MoveJ";
  }

  static const char* value(const ::robot_package::MoveJ&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::MoveJRequest> should match
// service_traits::MD5Sum< ::robot_package::MoveJ >
template<>
struct MD5Sum< ::robot_package::MoveJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::MoveJ >::value();
  }
  static const char* value(const ::robot_package::MoveJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::MoveJRequest> should match
// service_traits::DataType< ::robot_package::MoveJ >
template<>
struct DataType< ::robot_package::MoveJRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::MoveJ >::value();
  }
  static const char* value(const ::robot_package::MoveJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::MoveJResponse> should match
// service_traits::MD5Sum< ::robot_package::MoveJ >
template<>
struct MD5Sum< ::robot_package::MoveJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::MoveJ >::value();
  }
  static const char* value(const ::robot_package::MoveJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::MoveJResponse> should match
// service_traits::DataType< ::robot_package::MoveJ >
template<>
struct DataType< ::robot_package::MoveJResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::MoveJ >::value();
  }
  static const char* value(const ::robot_package::MoveJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_MOVEJ_H
