// Generated by gencpp from file robot_package/MoveABSJGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_MOVEABSJGOAL_H
#define ROBOT_PACKAGE_MESSAGE_MOVEABSJGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct MoveABSJGoal_
{
  typedef MoveABSJGoal_<ContainerAllocator> Type;

  MoveABSJGoal_()
    : arm_index(0)
    , joints()
    , vel(0.0)  {
    }
  MoveABSJGoal_(const ContainerAllocator& _alloc)
    : arm_index(0)
    , joints(_alloc)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _arm_index_type;
  _arm_index_type arm_index;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joints_type;
  _joints_type joints;

   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::robot_package::MoveABSJGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::MoveABSJGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveABSJGoal_

typedef ::robot_package::MoveABSJGoal_<std::allocator<void> > MoveABSJGoal;

typedef boost::shared_ptr< ::robot_package::MoveABSJGoal > MoveABSJGoalPtr;
typedef boost::shared_ptr< ::robot_package::MoveABSJGoal const> MoveABSJGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::MoveABSJGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::MoveABSJGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::MoveABSJGoal_<ContainerAllocator1> & lhs, const ::robot_package::MoveABSJGoal_<ContainerAllocator2> & rhs)
{
  return lhs.arm_index == rhs.arm_index &&
    lhs.joints == rhs.joints &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::MoveABSJGoal_<ContainerAllocator1> & lhs, const ::robot_package::MoveABSJGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::MoveABSJGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::MoveABSJGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::MoveABSJGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df8d4c44bf84b41df5e79538a31971f6";
  }

  static const char* value(const ::robot_package::MoveABSJGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf8d4c44bf84b41dULL;
  static const uint64_t static_value2 = 0xf5e79538a31971f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/MoveABSJGoal";
  }

  static const char* value(const ::robot_package::MoveABSJGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal 消息\n"
"int8 arm_index\n"
"float32[] joints\n"
"float32 vel\n"
;
  }

  static const char* value(const ::robot_package::MoveABSJGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_index);
      stream.next(m.joints);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveABSJGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::MoveABSJGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::MoveABSJGoal_<ContainerAllocator>& v)
  {
    s << indent << "arm_index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.arm_index);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints[i]);
    }
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_MOVEABSJGOAL_H
