// Generated by gencpp from file robot_package/MoveLResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_MOVELRESPONSE_H
#define ROBOT_PACKAGE_MESSAGE_MOVELRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct MoveLResponse_
{
  typedef MoveLResponse_<ContainerAllocator> Type;

  MoveLResponse_()
    : result(0)
    , strRt()  {
    }
  MoveLResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , strRt(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _strRt_type;
  _strRt_type strRt;





  typedef boost::shared_ptr< ::robot_package::MoveLResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::MoveLResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLResponse_

typedef ::robot_package::MoveLResponse_<std::allocator<void> > MoveLResponse;

typedef boost::shared_ptr< ::robot_package::MoveLResponse > MoveLResponsePtr;
typedef boost::shared_ptr< ::robot_package::MoveLResponse const> MoveLResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::MoveLResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::MoveLResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::MoveLResponse_<ContainerAllocator1> & lhs, const ::robot_package::MoveLResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.strRt == rhs.strRt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::MoveLResponse_<ContainerAllocator1> & lhs, const ::robot_package::MoveLResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::MoveLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::MoveLResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::MoveLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::MoveLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::MoveLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::MoveLResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::MoveLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c90c415abe5c551e00af23b2a60609a";
  }

  static const char* value(const ::robot_package::MoveLResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c90c415abe5c551ULL;
  static const uint64_t static_value2 = 0xe00af23b2a60609aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::MoveLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/MoveLResponse";
  }

  static const char* value(const ::robot_package::MoveLResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::MoveLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"string strRt\n"
;
  }

  static const char* value(const ::robot_package::MoveLResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::MoveLResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.strRt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::MoveLResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::MoveLResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "strRt: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.strRt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_MOVELRESPONSE_H
