// Generated by gencpp from file robot_package/ServoRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_SERVOREQUEST_H
#define ROBOT_PACKAGE_MESSAGE_SERVOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct ServoRequest_
{
  typedef ServoRequest_<ContainerAllocator> Type;

  ServoRequest_()
    : arm_index(0)
    , servoState(false)  {
    }
  ServoRequest_(const ContainerAllocator& _alloc)
    : arm_index(0)
    , servoState(false)  {
  (void)_alloc;
    }



   typedef int8_t _arm_index_type;
  _arm_index_type arm_index;

   typedef uint8_t _servoState_type;
  _servoState_type servoState;





  typedef boost::shared_ptr< ::robot_package::ServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::ServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServoRequest_

typedef ::robot_package::ServoRequest_<std::allocator<void> > ServoRequest;

typedef boost::shared_ptr< ::robot_package::ServoRequest > ServoRequestPtr;
typedef boost::shared_ptr< ::robot_package::ServoRequest const> ServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::ServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::ServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::ServoRequest_<ContainerAllocator1> & lhs, const ::robot_package::ServoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.arm_index == rhs.arm_index &&
    lhs.servoState == rhs.servoState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::ServoRequest_<ContainerAllocator1> & lhs, const ::robot_package::ServoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::ServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::ServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c376ed0540e588c71e379fca3f7c5604";
  }

  static const char* value(const ::robot_package::ServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc376ed0540e588c7ULL;
  static const uint64_t static_value2 = 0x1e379fca3f7c5604ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/ServoRequest";
  }

  static const char* value(const ::robot_package::ServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 arm_index\n"
"bool servoState\n"
"\n"
;
  }

  static const char* value(const ::robot_package::ServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::ServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_index);
      stream.next(m.servoState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::ServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::ServoRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm_index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.arm_index);
    s << indent << "servoState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servoState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_SERVOREQUEST_H
