// Generated by gencpp from file robot_package/Servo.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_SERVO_H
#define ROBOT_PACKAGE_MESSAGE_SERVO_H

#include <ros/service_traits.h>


#include <robot_package/ServoRequest.h>
#include <robot_package/ServoResponse.h>


namespace robot_package
{

struct Servo
{

typedef ServoRequest Request;
typedef ServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Servo
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::Servo > {
  static const char* value()
  {
    return "b15f459093083ca0158fd62e9d4b9e1d";
  }

  static const char* value(const ::robot_package::Servo&) { return value(); }
};

template<>
struct DataType< ::robot_package::Servo > {
  static const char* value()
  {
    return "robot_package/Servo";
  }

  static const char* value(const ::robot_package::Servo&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::ServoRequest> should match
// service_traits::MD5Sum< ::robot_package::Servo >
template<>
struct MD5Sum< ::robot_package::ServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::Servo >::value();
  }
  static const char* value(const ::robot_package::ServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::ServoRequest> should match
// service_traits::DataType< ::robot_package::Servo >
template<>
struct DataType< ::robot_package::ServoRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::Servo >::value();
  }
  static const char* value(const ::robot_package::ServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::ServoResponse> should match
// service_traits::MD5Sum< ::robot_package::Servo >
template<>
struct MD5Sum< ::robot_package::ServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::Servo >::value();
  }
  static const char* value(const ::robot_package::ServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::ServoResponse> should match
// service_traits::DataType< ::robot_package::Servo >
template<>
struct DataType< ::robot_package::ServoResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::Servo >::value();
  }
  static const char* value(const ::robot_package::ServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_SERVO_H
