// Generated by gencpp from file robot_package/VehicleControl.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_VEHICLECONTROL_H
#define ROBOT_PACKAGE_MESSAGE_VEHICLECONTROL_H

#include <ros/service_traits.h>


#include <robot_package/VehicleControlRequest.h>
#include <robot_package/VehicleControlResponse.h>


namespace robot_package
{

struct VehicleControl
{

typedef VehicleControlRequest Request;
typedef VehicleControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VehicleControl
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::VehicleControl > {
  static const char* value()
  {
    return "32b3b53d0e476262a13481b20e7b9bb8";
  }

  static const char* value(const ::robot_package::VehicleControl&) { return value(); }
};

template<>
struct DataType< ::robot_package::VehicleControl > {
  static const char* value()
  {
    return "robot_package/VehicleControl";
  }

  static const char* value(const ::robot_package::VehicleControl&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::VehicleControlRequest> should match
// service_traits::MD5Sum< ::robot_package::VehicleControl >
template<>
struct MD5Sum< ::robot_package::VehicleControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::VehicleControl >::value();
  }
  static const char* value(const ::robot_package::VehicleControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::VehicleControlRequest> should match
// service_traits::DataType< ::robot_package::VehicleControl >
template<>
struct DataType< ::robot_package::VehicleControlRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::VehicleControl >::value();
  }
  static const char* value(const ::robot_package::VehicleControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::VehicleControlResponse> should match
// service_traits::MD5Sum< ::robot_package::VehicleControl >
template<>
struct MD5Sum< ::robot_package::VehicleControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::VehicleControl >::value();
  }
  static const char* value(const ::robot_package::VehicleControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::VehicleControlResponse> should match
// service_traits::DataType< ::robot_package::VehicleControl >
template<>
struct DataType< ::robot_package::VehicleControlResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::VehicleControl >::value();
  }
  static const char* value(const ::robot_package::VehicleControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_VEHICLECONTROL_H
