// Generated by gencpp from file robot_package/VehicleServo.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_VEHICLESERVO_H
#define ROBOT_PACKAGE_MESSAGE_VEHICLESERVO_H

#include <ros/service_traits.h>


#include <robot_package/VehicleServoRequest.h>
#include <robot_package/VehicleServoResponse.h>


namespace robot_package
{

struct VehicleServo
{

typedef VehicleServoRequest Request;
typedef VehicleServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VehicleServo
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::VehicleServo > {
  static const char* value()
  {
    return "27e94be142d556e1a0d52326b0de189d";
  }

  static const char* value(const ::robot_package::VehicleServo&) { return value(); }
};

template<>
struct DataType< ::robot_package::VehicleServo > {
  static const char* value()
  {
    return "robot_package/VehicleServo";
  }

  static const char* value(const ::robot_package::VehicleServo&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::VehicleServoRequest> should match
// service_traits::MD5Sum< ::robot_package::VehicleServo >
template<>
struct MD5Sum< ::robot_package::VehicleServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::VehicleServo >::value();
  }
  static const char* value(const ::robot_package::VehicleServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::VehicleServoRequest> should match
// service_traits::DataType< ::robot_package::VehicleServo >
template<>
struct DataType< ::robot_package::VehicleServoRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::VehicleServo >::value();
  }
  static const char* value(const ::robot_package::VehicleServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::VehicleServoResponse> should match
// service_traits::MD5Sum< ::robot_package::VehicleServo >
template<>
struct MD5Sum< ::robot_package::VehicleServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::VehicleServo >::value();
  }
  static const char* value(const ::robot_package::VehicleServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::VehicleServoResponse> should match
// service_traits::DataType< ::robot_package::VehicleServo >
template<>
struct DataType< ::robot_package::VehicleServoResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::VehicleServo >::value();
  }
  static const char* value(const ::robot_package::VehicleServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_VEHICLESERVO_H
