// Generated by gencpp from file robot_package/VehicleCommModel.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_VEHICLECOMMMODEL_H
#define ROBOT_PACKAGE_MESSAGE_VEHICLECOMMMODEL_H

#include <ros/service_traits.h>


#include <robot_package/VehicleCommModelRequest.h>
#include <robot_package/VehicleCommModelResponse.h>


namespace robot_package
{

struct VehicleCommModel
{

typedef VehicleCommModelRequest Request;
typedef VehicleCommModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VehicleCommModel
} // namespace robot_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_package::VehicleCommModel > {
  static const char* value()
  {
    return "e14465039f2205faa968203b38699079";
  }

  static const char* value(const ::robot_package::VehicleCommModel&) { return value(); }
};

template<>
struct DataType< ::robot_package::VehicleCommModel > {
  static const char* value()
  {
    return "robot_package/VehicleCommModel";
  }

  static const char* value(const ::robot_package::VehicleCommModel&) { return value(); }
};


// service_traits::MD5Sum< ::robot_package::VehicleCommModelRequest> should match
// service_traits::MD5Sum< ::robot_package::VehicleCommModel >
template<>
struct MD5Sum< ::robot_package::VehicleCommModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::VehicleCommModel >::value();
  }
  static const char* value(const ::robot_package::VehicleCommModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::VehicleCommModelRequest> should match
// service_traits::DataType< ::robot_package::VehicleCommModel >
template<>
struct DataType< ::robot_package::VehicleCommModelRequest>
{
  static const char* value()
  {
    return DataType< ::robot_package::VehicleCommModel >::value();
  }
  static const char* value(const ::robot_package::VehicleCommModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_package::VehicleCommModelResponse> should match
// service_traits::MD5Sum< ::robot_package::VehicleCommModel >
template<>
struct MD5Sum< ::robot_package::VehicleCommModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_package::VehicleCommModel >::value();
  }
  static const char* value(const ::robot_package::VehicleCommModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_package::VehicleCommModelResponse> should match
// service_traits::DataType< ::robot_package::VehicleCommModel >
template<>
struct DataType< ::robot_package::VehicleCommModelResponse>
{
  static const char* value()
  {
    return DataType< ::robot_package::VehicleCommModel >::value();
  }
  static const char* value(const ::robot_package::VehicleCommModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_VEHICLECOMMMODEL_H
