// Generated by gencpp from file robot_package/VehicleServoRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_VEHICLESERVOREQUEST_H
#define ROBOT_PACKAGE_MESSAGE_VEHICLESERVOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct VehicleServoRequest_
{
  typedef VehicleServoRequest_<ContainerAllocator> Type;

  VehicleServoRequest_()
    : servoState(false)  {
    }
  VehicleServoRequest_(const ContainerAllocator& _alloc)
    : servoState(false)  {
  (void)_alloc;
    }



   typedef uint8_t _servoState_type;
  _servoState_type servoState;





  typedef boost::shared_ptr< ::robot_package::VehicleServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::VehicleServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleServoRequest_

typedef ::robot_package::VehicleServoRequest_<std::allocator<void> > VehicleServoRequest;

typedef boost::shared_ptr< ::robot_package::VehicleServoRequest > VehicleServoRequestPtr;
typedef boost::shared_ptr< ::robot_package::VehicleServoRequest const> VehicleServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::VehicleServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::VehicleServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::VehicleServoRequest_<ContainerAllocator1> & lhs, const ::robot_package::VehicleServoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.servoState == rhs.servoState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::VehicleServoRequest_<ContainerAllocator1> & lhs, const ::robot_package::VehicleServoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::VehicleServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::VehicleServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::VehicleServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c8e2b4bfe846d0ba5e9035cc5579db0";
  }

  static const char* value(const ::robot_package::VehicleServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c8e2b4bfe846d0bULL;
  static const uint64_t static_value2 = 0xa5e9035cc5579db0ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/VehicleServoRequest";
  }

  static const char* value(const ::robot_package::VehicleServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool servoState\n"
;
  }

  static const char* value(const ::robot_package::VehicleServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servoState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::VehicleServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::VehicleServoRequest_<ContainerAllocator>& v)
  {
    s << indent << "servoState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servoState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_VEHICLESERVOREQUEST_H
