// Generated by gencpp from file robot_package/VehicleCommModelRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_PACKAGE_MESSAGE_VEHICLECOMMMODELREQUEST_H
#define ROBOT_PACKAGE_MESSAGE_VEHICLECOMMMODELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_package
{
template <class ContainerAllocator>
struct VehicleCommModelRequest_
{
  typedef VehicleCommModelRequest_<ContainerAllocator> Type;

  VehicleCommModelRequest_()
    : model(0)  {
    }
  VehicleCommModelRequest_(const ContainerAllocator& _alloc)
    : model(0)  {
  (void)_alloc;
    }



   typedef int8_t _model_type;
  _model_type model;





  typedef boost::shared_ptr< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleCommModelRequest_

typedef ::robot_package::VehicleCommModelRequest_<std::allocator<void> > VehicleCommModelRequest;

typedef boost::shared_ptr< ::robot_package::VehicleCommModelRequest > VehicleCommModelRequestPtr;
typedef boost::shared_ptr< ::robot_package::VehicleCommModelRequest const> VehicleCommModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_package::VehicleCommModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_package::VehicleCommModelRequest_<ContainerAllocator1> & lhs, const ::robot_package::VehicleCommModelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model == rhs.model;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_package::VehicleCommModelRequest_<ContainerAllocator1> & lhs, const ::robot_package::VehicleCommModelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06f46787456bfa982a758ce33a55e127";
  }

  static const char* value(const ::robot_package::VehicleCommModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06f46787456bfa98ULL;
  static const uint64_t static_value2 = 0x2a758ce33a55e127ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_package/VehicleCommModelRequest";
  }

  static const char* value(const ::robot_package::VehicleCommModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 model\n"
" \n"
;
  }

  static const char* value(const ::robot_package::VehicleCommModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleCommModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_package::VehicleCommModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_package::VehicleCommModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "model: ";
    Printer<int8_t>::stream(s, indent + "  ", v.model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PACKAGE_MESSAGE_VEHICLECOMMMODELREQUEST_H
