#ifndef ROBOTCONSYS_TYPEDEF_H
#define ROBOTCONSYS_TYPEDEF_H

#include "Common_Define.h"

namespace rclib{

#define TMP_FILE_DIR_STRING string("tmpRobotConSys")+string(PATH_SEP_STRING)
#define ROBOT_PARAMETER_NAME_STRING string("RobotParameter.xml")
#define ROBOT_PREFERENCE_NAME_STRING string("RobotPreference.xml")
#define ROBOT_FRAME_NAME_STRING string("RobotFrame.xml")
#define ROBOTCONSYS_PREFERENCE_NAME_STRING string("RobotConSysPreference.xml")
#define ROBOT_PROGRAM_NAME_STRING string("RobotProgram")
#define ROBOTCONSYS_MODBUS_LEN 200
#define ROBOTCONSYS_MAX_ARM 4
#define ROBOTCONSYS_MAX_VEHICLE 4
#define ROBOTCONSYS_PERIPHERAL_NUM 10

enum ROBOTCONSYS_ARM_INDEX{ROBOTCONSYS_ARM_1 = 0, ROBOTCONSYS_ARM_2, ROBOTCONSYS_ARM_3, ROBOTCONSYS_ARM_4};
enum ROBOTCONSYS_VEHICLE_INDEX{ROBOTCONSYS_VEHICLE_1 = 0, ROBOTCONSYS_VEHICLE_2, ROBOTCONSYS_VEHICLE_3, ROBOTCONSYS_VEHICLE_4};
enum ROBOTCONSYS_PERIPHERAL_DATA_INDEX{	ROBOTCONSYS_PERIPHERAL_DATA_1, 
										ROBOTCONSYS_PERIPHERAL_DATA_2,
										ROBOTCONSYS_PERIPHERAL_DATA_3, 
										ROBOTCONSYS_PERIPHERAL_DATA_4,
										ROBOTCONSYS_PERIPHERAL_DATA_5, 
										ROBOTCONSYS_PERIPHERAL_DATA_6,
										ROBOTCONSYS_PERIPHERAL_DATA_7, 
										ROBOTCONSYS_PERIPHERAL_DATA_8,
										ROBOTCONSYS_PERIPHERAL_DATA_9, 
										ROBOTCONSYS_PERIPHERAL_DATA_10};

}

#endif
