(cl:defpackage robot_package-msg
  (:use )
  (:export
   "<MOVEABSJACTION>"
   "MOVEABSJACTION"
   "<MOVEABSJACTIONFEEDBACK>"
   "MOVEABSJACTIONFEEDBACK"
   "<MOVEABSJACTIONGOAL>"
   "MOVEABSJACTIONGOAL"
   "<MOVEABSJACTIONRESULT>"
   "MOVEABSJACTIONRESULT"
   "<MOVEABSJFEEDBACK>"
   "MOVEABSJFEEDBACK"
   "<MOVEABSJGOAL>"
   "MOVEABSJGOAL"
   "<MOVEABSJRESULT>"
   "MOVEABSJRESULT"
   "<TR_ARM_MSG>"
   "TR_ARM_MSG"
   "<TR_VEHICLE_IMU_MSG>"
   "TR_VEHICLE_IMU_MSG"
   "<TR_VEHICLE_MSG>"
   "TR_VEHICLE_MSG"
  ))

