; Auto-generated. Do not edit!


(cl:in-package robot_package-msg)


;//! \htmlinclude MoveABSJFeedback.msg.html

(cl:defclass <MoveABSJFeedback> (roslisp-msg-protocol:ros-message)
  ((current_state
    :reader current_state
    :initarg :current_state
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveABSJFeedback (<MoveABSJFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveABSJFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveABSJFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_package-msg:<MoveABSJFeedback> is deprecated: use robot_package-msg:MoveABSJFeedback instead.")))

(cl:ensure-generic-function 'current_state-val :lambda-list '(m))
(cl:defmethod current_state-val ((m <MoveABSJFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_package-msg:current_state-val is deprecated.  Use robot_package-msg:current_state instead.")
  (current_state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveABSJFeedback>) ostream)
  "Serializes a message object of type '<MoveABSJFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveABSJFeedback>) istream)
  "Deserializes a message object of type '<MoveABSJFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_state) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveABSJFeedback>)))
  "Returns string type for a message object of type '<MoveABSJFeedback>"
  "robot_package/MoveABSJFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveABSJFeedback)))
  "Returns string type for a message object of type 'MoveABSJFeedback"
  "robot_package/MoveABSJFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveABSJFeedback>)))
  "Returns md5sum for a message object of type '<MoveABSJFeedback>"
  "250debf4867cbd8be718efdde213baf6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveABSJFeedback)))
  "Returns md5sum for a message object of type 'MoveABSJFeedback"
  "250debf4867cbd8be718efdde213baf6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveABSJFeedback>)))
  "Returns full string definition for message of type '<MoveABSJFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback 消息~%float32 current_state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveABSJFeedback)))
  "Returns full string definition for message of type 'MoveABSJFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback 消息~%float32 current_state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveABSJFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveABSJFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveABSJFeedback
    (cl:cons ':current_state (current_state msg))
))
