; Auto-generated. Do not edit!


(cl:in-package robot_package-msg)


;//! \htmlinclude MoveABSJResult.msg.html

(cl:defclass <MoveABSJResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass MoveABSJResult (<MoveABSJResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveABSJResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveABSJResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_package-msg:<MoveABSJResult> is deprecated: use robot_package-msg:MoveABSJResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <MoveABSJResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_package-msg:result-val is deprecated.  Use robot_package-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveABSJResult>) ostream)
  "Serializes a message object of type '<MoveABSJResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveABSJResult>) istream)
  "Deserializes a message object of type '<MoveABSJResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveABSJResult>)))
  "Returns string type for a message object of type '<MoveABSJResult>"
  "robot_package/MoveABSJResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveABSJResult)))
  "Returns string type for a message object of type 'MoveABSJResult"
  "robot_package/MoveABSJResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveABSJResult>)))
  "Returns md5sum for a message object of type '<MoveABSJResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveABSJResult)))
  "Returns md5sum for a message object of type 'MoveABSJResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveABSJResult>)))
  "Returns full string definition for message of type '<MoveABSJResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result 消息~%int32 result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveABSJResult)))
  "Returns full string definition for message of type 'MoveABSJResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result 消息~%int32 result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveABSJResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveABSJResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveABSJResult
    (cl:cons ':result (result msg))
))
